version: "3"

services:
  react-docker-example:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./public:/react-docker-example/public
      - ./src:/react-docker-example/src
    working_dir: /react-docker-example
    command: ["npm", "run","start"]